"""create material_returns table

Revision ID: 512c49a08eba
Revises: dcf0b5ccf6bf
Create Date: 2026-08-02 16:29:12.631762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512c49a08eba'
down_revision: Union[str, Sequence[str], None] = 'dcf0b5ccf6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_issue_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['material_issue_id'], ['material_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_returns_id'), 'material_returns', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_returns_id'), table_name='material_returns')
    op.drop_table('material_returns')
    # ### end Alembic commands ###
