"""add payroll status and history fields

Revision ID: 5316178d331b
Revises: b212c78b449a
Create Date: 2026-08-24 08:17:33.413557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5316178d331b'
down_revision: Union[str, Sequence[str], None] = 'b212c78b449a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advance_transactions_id'), table_name='advance_transactions')
    op.drop_table('advance_transactions')
    op.drop_index(op.f('ix_advances_id'), table_name='advances')
    op.drop_table('advances')
    op.alter_column('contractors', 'experience_years',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contractors', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('payrolls', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('payrolls', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('payrolls', sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payrolls', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_payrolls_employee_id'), 'payrolls', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payrolls_status'), 'payrolls', ['status'], unique=False)
    op.create_unique_constraint('uq_payroll_employee_year_month', 'payrolls', ['employee_id', 'year', 'month'])
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('salary_structures', 'hra',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('salary_structures', 'allowance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('salary_structures', 'pf',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('salary_structures', 'professional_tax',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salary_structures', 'professional_tax',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('salary_structures', 'pf',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('salary_structures', 'allowance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('salary_structures', 'hra',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_constraint('uq_payroll_employee_year_month', 'payrolls', type_='unique')
    op.drop_index(op.f('ix_payrolls_status'), table_name='payrolls')
    op.drop_index(op.f('ix_payrolls_employee_id'), table_name='payrolls')
    op.drop_column('payrolls', 'paid_at')
    op.drop_column('payrolls', 'finalized_at')
    op.drop_column('payrolls', 'created_at')
    op.drop_column('payrolls', 'status')
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('contractors', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('contractors', 'experience_years',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('advances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('advance_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('advance_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('remaining_amount', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('advances_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('advances_pkey')),
    sa.UniqueConstraint('advance_code', name=op.f('advances_advance_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_advances_id'), 'advances', ['id'], unique=False)
    op.create_table('advance_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('advance_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['advance_id'], ['advances.id'], name=op.f('advance_transactions_advance_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('advance_transactions_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('advance_transactions_pkey'))
    )
    op.create_index(op.f('ix_advance_transactions_id'), 'advance_transactions', ['id'], unique=False)
    # ### end Alembic commands ###
