"""add unique constraint to project_employees

Revision ID: 715281ee3543
Revises: b03c35a5c818
Create Date: 2026-07-29 12:24:38.159945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715281ee3543'
down_revision: Union[str, Sequence[str], None] = 'b03c35a5c818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_employee', 'project_employees', ['project_id', 'employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_employee', 'project_employees', type_='unique')
    # ### end Alembic commands ###
