"""create contractor table

Revision ID: 458f30322716
Revises: ef0ae1b687e6
Create Date: 2026-07-28 09:44:40.097256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458f30322716'
down_revision: Union[str, Sequence[str], None] = 'ef0ae1b687e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('contractor_name', sa.String(length=100), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('licence_number', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contractor_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('gst_number'),
    sa.UniqueConstraint('licence_number'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_index(op.f('ix_contractors_id'), 'contractors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contractors_id'), table_name='contractors')
    op.drop_table('contractors')
    # ### end Alembic commands ###
