"""create employee table

Revision ID: ef0ae1b687e6
Revises: 5871a831663b
Create Date: 2026-07-27 16:18:39.442077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef0ae1b687e6'
down_revision: Union[str, Sequence[str], None] = '5871a831663b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_id', sa.String(length=20), nullable=False))
    op.add_column('employees', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('department', sa.String(length=100), nullable=False))
    op.add_column('employees', sa.Column('salary', sa.Float(), nullable=False))
    op.add_column('employees', sa.Column('joining_date', sa.Date(), nullable=False))
    op.alter_column('employees', 'mobile_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('employees', 'designation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(op.f('employees_employee_code_key'), 'employees', type_='unique')
    op.create_unique_constraint(None, 'employees', ['employee_id'])
    op.create_unique_constraint(None, 'employees', ['email'])
    op.drop_column('employees', 'employee_code')
    op.drop_column('employees', 'daily_wage')
    op.drop_column('employees', 'address')
    op.drop_column('employees', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('daily_wage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('employee_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_constraint(None, 'employees', type_='unique')
    op.create_unique_constraint(op.f('employees_employee_code_key'), 'employees', ['employee_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('employees', 'designation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('employees', 'mobile_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_column('employees', 'joining_date')
    op.drop_column('employees', 'salary')
    op.drop_column('employees', 'department')
    op.drop_column('employees', 'email')
    op.drop_column('employees', 'employee_id')
    # ### end Alembic commands ###
